server:
  port: 9118
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
eureka:
  instance:
    preferIpAddress: true
    app-group-name: base
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.173.130:8761/eureka/
management:
  endpoints:
    web:
      basePath: /
      expose: [metrics,info,health]
info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: 1.0.0
spring:
  application:
    name: config-services
  cloud:
    config:
      server:
        prefix: config
    inetutils:
      preferredNetworks:
        - 192.168.173
  zipkin:
    baseUrl: http://192.168.173.130:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  data:
    mongodb:
      host: 192.168.173.130:27515
      database: youi3-common
      username: query
      password: query123

security:
  oauth2:
    client:
      accessTokenUri: http://http://192.168.173.130:8868/oauth/token
      userAuthorizationUri: http://http://192.168.173.130:8868/oauth/authorize
    resource:
      id: ${spring.application.name}
      user-info-uri: http://http://192.168.173.130:8868/oauth/client
      prefer-token-info: false