server:
  port: 8258
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
eureka:
  instance:
    preferIpAddress: true
    app-group-name: base
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.173.130:8761/eureka/
management:
  endpoints:
    web:
      basePath: /
      expose: [metrics,info,health]
info:
  app:
    name: ${spring.application.name}
    description: stats gather task
    version: 1.0.0
spring:
  application:
    name: base-services
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168.173
#    config:
#      discovery:
#        enabled: true
#        service-id: config-services
#      label: master
  data:
    mongodb:
      host: 192.168.173.130:27515
      database: youi3-common
      username: query
      password: query123
security:
  oauth2:
    client:
      accessTokenUri: http://192.168.173.130:8868/oauth/token
      userAuthorizationUri: http://192.168.173.130:8868/oauth/authorize
    resource:
      id: ${spring.application.name}
      user-info-uri: http://192.168.173.130:8868/oauth/client
      prefer-token-info: false