server:
  port: 9112
  session:
    cookie:
      name: USESSIONID
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      basePath: /
      expose: [metrics,info,health]
info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: 1.0.0

spring:
  application:
    name: file-services
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168.173
  servlet:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 1024MB # 设置单个文件的最大长度
      max-request-size: 1024MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /Users/zhouyi/doc/files_backup  # 上传的临时目录
  data:
    mongodb:
      host: 192.168.173.130:27515
      username: query
      password: query123
      database: stats2-common
  zipkin:
    baseUrl: http://192.168.173.130:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8868/oauth/token
      userAuthorizationUri: http://localhost:8868/oauth/authorize
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8868/oauth/client
      prefer-token-info: false