server:
  port: 8277
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      basePath: /
      expose: [metrics,info,health]
info:
  app:
    name: ${spring.application.name}
    description: stats gather task
    version: 1.0.0

spring:
  datasource:
    url: jdbc:mysql://192.168.173.130:3307/youi3-common?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: filing
    password: Gwssi@)16
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168.173
  jpa:
    hibernate:
      ddl-auto: none
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8868/oauth/token
      userAuthorizationUri: http://localhost:8868/oauth/authorize
      client-secret: 123456
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8868/oauth/client
      prefer-token-info: false

youi:
  server:
    caller:
      keystoreFile: classpath:keys/youi.keystore
      keystoreName: youi
      keystorePassword: youi01
      apiBaseUri: http://localhost:8080